### PR TITLE
Fix unmet dependency in RN v0.64.0

### PR DESCRIPTION
**Pull request by yaqoobhisbani**
Fixes [#107](https://github.com/react-native-masked-view/masked-view/issues/107)

### CODE REVIEW

**Comment by hussainahmad** [comment]
please update this and should go live today as unable to start project

**Review by sherebiahtishbi — APPROVED** [review]

**Comment by sherebiahtishbi** [comment]
As it was looking for 1 review/approval so I reviewed the change and approved it....lets see where it goes from here now! :)

**Comment by sherebiahtishbi** [comment]
All, if you are stuck you can move project to 16.13.1 if it is less work for you.

**Comment by FonDorn** [comment]
@react-native-masked-view/masked-view is updated

**Pull request closed without merging**
