### PR TITLE
Performance fix for Android by enabling hardware acceleration

### PR DESCRIPTION
**Pull request by k-ibr**
# Overview

We were having a lot of issues with performance on android such as explained in #110 but also some other users are facing in #88. By enabling hardware acceleration (default is set to software and results in extremely poor performance) for the Android Canvas we managed to solve these issues entirely. The project ran at 60fps, similar to IOS.

Here is a video showing software and hardware in action:
[Hardware Acceleration OFF](https://www.dropbox.com/s/tp92z4mhwgje2t6/software.webm?dl=0) - performance is so bad it's impacting the recording, sorry.
[Hardware Acceleration ON](https://www.dropbox.com/s/7hc0enqmitf0ijh/hardware.webm?dl=0)

# Test Plan

When lots of re-renders are happening to a screen, the default code has extremely poor performance (as seen in the video). You can test this by creating a simple screen with a few MaskedView views and animating a few elements (which require for constant re-rendering at 60fps). You will notice this will result in bad performance overall only on Android and no issues on IOS.

It's a simple fix but it gets the results we have been looking for in our project.

### CODE REVIEW

**Comment by k-ibr** [comment]
@Naturalclar this fixes some huge performance issues for Android users, would be nice if we can get this merged asap so I can get to work on an Expo PR, since that will take the necessary time as well.

**Review by FonDorn — APPROVED** [review]

**Comment by k-ibr** [comment]
Thanks for the approval @FonDorn 👏 can't wait to finally have this fix merged so I can start on the Expo PR

**Comment by FonDorn** [comment]
@k-ibr thanks you. Please go ahead

**Comment by k-ibr** [comment]
Thank you, what is your estimation for a release including this fix?

**Comment by k-ibr** [comment]
@FonDorn @Naturalclar can someone also please publish latest version to NPM? thanks!

**Comment by Naturalclar** [comment]
@k-ibr done! Should be published on npm now, thanks for the change :+1:

**Pull request merged**
