### PR TITLE
Fix black background on android

### LINKED ISSUE #226: Android broken background with react-native 0.75.1
image

Left is android sim and right is iOS. I cant get rid of the black background on android since upgrading to RN 0.75.1. Prior versions worked great!!

Any ideas on how to fix this?

### PR DESCRIPTION
**Pull request by alanjhughes**
# Overview
Closes #226
Calling `setLayerType` from `setRenderingMode` and passing null as the paint reference will cause the default paint to be used which will have it's `PorterDuffXfermode` set to `SRC_OVER`. This causes the incorrect result.

I've added a new `mRenderingMode` property that is used to call `setLayerType` from `dispatchDraw` where we have a paint reference with the correct PorterDuffXfermode set.

# Test Plan
I've updated the example app to use 0.75 and tested both platforms on both architectures.

### CODE REVIEW

**Review by crashzky — APPROVED** [review]

**Comment by samueljim** [comment]
LGTM

**Review by samueljim — APPROVED** [review]

**Comment by samueljim** [comment]
I'm currently using this in my package.json for all those who need this fix 
```
"@react-native-masked-view/masked-view": "https://github.com/react-native-masked-view/masked-view/archive/edee2e76a3ead5135d8328ec5c5073415e4c9dbe.tar.gz",
```

**Comment by samueljim** [comment]
BUMP

**Review by AliRezaBeigy — APPROVED** [review]
as @samueljim tested it's ok
i test it too and the black background issue goes away
@Naturalclar can you merge these change?

**Review by Naturalclar — APPROVED** [review]
thank you so much!

**Pull request merged**
